# Generated by Django 3.0.2 on 2020-01-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudosci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
