# Generated by Django 3.0.2 on 2020-01-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pseudosci', '0002_auto_20200108_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='count',
            new_name='weight',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Result')),
                ('description', models.TextField(unique=True, verbose_name='Description')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pseudosci.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pseudosci.Result'),
        ),
    ]
