# Generated by Django 3.0.2 on 2020-01-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pseudosci', '0004_auto_20200109_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='weight',
        ),
    ]
