# Generated by Django 3.0.2 on 2020-01-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudosci', '0006_auto_20200109_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='result',
        ),
        migrations.AddField(
            model_name='choice',
            name='result',
            field=models.ManyToManyField(to='pseudosci.Result'),
        ),
    ]
